print('Welcome To The Letter Counter Python Program')
name = input("Hey, What's Your Name :\t ")
print("Welcome " + name + "!")
msg = input("Enter A Sentance " + name + ":\t")
letter = input("Enter The Letter Whoes Occurance You Need To Find Out: \t")
msg= msg.lower()
letter = letter.lower()
count = msg.count(letter)
print("\n" + name +"Your Sentance has " + str(count) + " " + letter +"'s in it")